export enum EnumScreens {
    Intro = "Intro",
    Start = "Start",
    Tutorial = "Tutorial",
    Game = "Game",
    Feedback = "Feedback",
    History = "History",
    Tutorials = "Tutorials",
    Stats = "Stats",
    PlaygroundMode = "Playground Mode",
}

export enum EnumTiers {
    Adept = "Adept",
    Scholar = "Scholar", 
    Savant = "Savant",
    Expert = "Expert",
    Mastermind = "Mastermind",
    Enlightened = "Enlightened",
    Visionary = "Visionary",
    Innovator = "Innovator",
    Genius = "Genius",
    Virtuoso = "Virtuoso",
    Luminary = "Luminary",
    Illuminator = "Illuminator",
    Prodigy = "Prodigy",
    Intuitive = "Intuitive",
    Oracle = "Oracle",
    Visionist = "Visionist",
    Sage = "Sage",
    Thinker = "Thinker",
    Philosopher = "Philosopher",
    Theorist = "Theorist",
    Mystic = "Mystic",
    Seer = "Seer",
    Transcendent = "Transcendent",
}